export enum Role {
  STUDENT = 'STUDENT',
  EDUCATOR = 'EDUCATOR',
  GUARDIAN = 'GUARDIAN',
  ADMIN = 'ADMIN',
}

export enum EducatorType {
  TEACHER = 'TEACHER',
  INTERPRETER = 'INTERPRETER',
}

export enum LibrasLevel {
  BASICO = 'BASICO',
  INTERMEDIARIO = 'INTERMEDIARIO',
  AVANCADO = 'AVANCADO',
  FLUENTE = 'FLUENTE',
}

export enum SchoolLevel {
  ENSINO_MEDIO_1 = 'ENSINO_MEDIO_1',
  ENSINO_MEDIO_2 = 'ENSINO_MEDIO_2',
  ENSINO_MEDIO_3 = 'ENSINO_MEDIO_3',
}

export enum ClassRole {
  STUDENT = 'STUDENT',
  FAMILY = 'FAMILY',
  INTERPRETER = 'INTERPRETER',
  ASSISTANT = 'ASSISTANT',
}
