export enum Role {
  STUDENT = 'STUDENT',
  EDUCATOR = 'EDUCATOR',
  INTERPRETER = 'INTERPRETER',
  GUARDIAN = 'GUARDIAN',
  ADMIN = 'ADMIN',
}

export enum LibrasLevel {
  BASICO = 'BASICO',
  INTERMEDIARIO = 'INTERMEDIARIO',
  AVANCADO = 'AVANCADO',
  FLUENTE = 'FLUENTE',
}